### ISSUE TITLE
Reporting button UX issues

### ISSUE THREAD

**Issue by leiya-lacey** [bradenfrazer/nintendle#1]
The button in the top right corner should be hidden or show a silly popup if you click it before you solve it. I had to look at the app code to figure out why it wasn't working.

**Comment by bradenfrazer** [comment]
This is a valid argument, as I could see how it could be confusing for users what that button does, and why it's disabled if they haven't spent much time in the app. I still like the idea of keeping it there & disabled (so the opposite problem doesn't occur - someone gets confused why the button was there at one point but now it's totally gone), but I will explore adding a label or tooltip there for clarity.
