### ISSUE TITLE
className is for class names not for css

### ISSUE THREAD

**Issue by leiya-lacey** [bradenfrazer/nintendle#2]
Noticed in app.tsx, could be present elsewhere. I would recommend making a global (s)css file and importing it.

**Comment by bradenfrazer** [comment]
Not sure how familiar you are with [Tailwind's utility-first approach](https://tailwindcss.com/docs/utility-first), but the "CSS as a class name" is intended as part of that implementation. Essentially Tailwind lets you write common CSS by using their pre-existing classes on your HTML/JSX.

All that said, it can be a bit confusing to read someone else's code if they are using Tailwind and you've never seen it before. It's really helpful for quickly spinning up small projects and getting some initial styling in. This project definitely straddles the line between that helpfulness and where it would just be better to manually style things in a separate S(CSS) file. As the project has grown, the amount of class names needed on some elements is 15-20 which makes the code harder to read and maintain.

I'll look into ripping out Tailwind from this project and writing the styling from scratch at some point in the future, as it will be easier to build on the functionality that way if/when this app ever scales more.
